### ISSUE TITLE
How can I use python3.7 as the python version?

### ISSUE THREAD

**Issue by zhangk430** [SeldonIO/MLServer#845]
Hello,
I'm currently building the docker image for one of my model but one of the dependencies require python3.7. However, the latest mlserver uses python3.8. May I ask if it's possible to use python3.7 when building the docker image and if so what's the best way to do?
Thank you!

**Comment by adriangonz** [comment]
Hey @zhangk430,

When using the `mlserver build` command, you are able to specify your environment through a Conda `environment.yaml` file. Since Conda manages full Python environments, this means that you can also specify your Python version on that `environment.yaml` file. 

So instead of a `requirements.txt`, you could have something like the following `environment.yaml` file:

```yaml
name: custom-env
channels:
    - conda-forge
dependencies:
    - python == 3.7
    - pip
    - .... # other deps
    - pip:
        - mlserver == 1.1.0
        - mlserver-sklearn == 1.1.0
```
